### ISSUE TITLE
USER STORY ANONYMOUS POSTING

### ISSUE THREAD

**Issue by BlueBindy** [BlueBindy/love-running#4]
**User story:** As a **user** I can **hide my identity when I post** so that I **retain confidentiality and privacy**

# Acceptance Criteria:
* A. I can post without submitting my user name
* B. I can review my post before submitting
* C. I can view my post after submitting

# Tasks
- [ ] Update the view: Create the HTML and CSS for the anonymous checkbox
- [ ] Update the controller function
- [ ] Update test unit scripts
- [ ] Test the functionality
